name: better_internet_conn_check_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  flutter: '>=3.38.1 <4.0.0'
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^7.1.1
  material_ui: ^0.0.1
  pmvvm: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
