name: better_internet_conn_check_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  flutter: '>=3.38.1 <4.0.0'
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  better_internet_connectivity_checker:
    path: ../

  connectivity_plus: 7.1.1
  gap: 3.0.1
  http: 1.6.0
  material_ui: 0.0.1
  pmvvm: 4.0.1
  tap_debouncer: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
